### ISSUE TITLE
Fails to build with CMake 4.2.1

### ISSUE THREAD

**Issue by owochle** [MiKTeX/miktex#1713]
Miktex fails to build using CMake 4.2.1 with the following error
```
/tmp/tmp.OdTKebGHFa/miktex/build/Programs/TeXAndFriends/hitex/hitex.c:88:10: fatal error: hb.h: No such file or directory
   88 | #include "hb.h"
      |          ^~~~~~
```
`hb.h` is present in the file tree but cmake seems to not be able to locate it

**Comment by owochle** [comment]
You can make it compile successfully by adding `-DUSE_SYSTEM_HARFBUZZ=FALSE -DUSE_SYSTEM_HARFBUZZ_ICU=FALSE` to use the bundled harfbuzz. I don't know what causes this behaviour, but this may help debugging the issue

**Comment by AvrahamTsaban** [comment]
Was the problem actually targeted?
